
language: g++

env:
  - TEST_SUITE=fast1
  - TEST_SUITE=fast2
  - TEST_SUITE=negative

addons:
  apt:
    packages:
    - autoconf-archive
    - libboost-all-dev
    - zlib1g-dev
    - libxml++2.6-dev
    - libreadline-dev
    - libxml2-utils
    - libxml-libxml-perl

script:
   - autoreconf -fi
   - ./configure
   - make
   - make check-$TEST_SUITE
