#!/bin/sh
#
# Shell script to generate all of the two- three- and four- piece
# tablebases from the XML config files in the xml/ directory.  It can
# be restarted and will pick up where it left off.  genctlfile.pl was
# used to create the XML config files to begin with.

XMLDIR=xml

# make sure the pawn configurations always come last, since they depend on the others

twos=kk.xml

threes="k[qrbn]k.xml kpk.xml"

fours="k[qrbn]k[qrbn].xml k[qrbnp]kp.xml kpkp.xml k[qrbn][qrbn]k.xml k[qrbn]pk.xml kppk.xml"

fives="k[qrbn][qrbn]k[qrbn].xml k[qrbn]pk[qrbn].xml k[qrbn][qrbn]kp.xml k[qrbn]pkp.xml kppk[qrbn].xml kppkp.xml k[qrbn][qrbn][qrbn]k.xml k[qrbn][qrbn]pk.xml k[qrbn]ppk.xml kpppk.xml"
#fives="k[qrbn][qrbn]k[qrbn].xml"

for xml in $(cd $XMLDIR; for i in $twos $threes $fours $fives; do ls $i 2>/dev/null; done); do
    htb=`echo $xml | sed s/xml/htb/`;
    xml=$XMLDIR/$xml
    if [ -f $xml -a ! -f $htb ]; then
	echo Starting $xml
	./hoffman -g $xml || exit
    fi
done
