#!/bin/sh

XMLDIR=xml

# make sure the pawn configurations always come last, since they depend on the others

twos=kk.xml

threes="k[qrbn]k.xml kpk.xml"

fours="k[qrbn]k[qrbn].xml k[qrbnp]kp.xml kpkp.xml k[qrbn][qrbn]k.xml k[qrbn]pk.xml kppk.xml"

fives="k[qrbn][qrbn]k[qrbn].xml k[qrbnp]pk[qrbn].xml kppk[qrbn].xml k[qrbn][qrbn]kp.xml k[qrbn]pkp.xml kppkp.xml k[qrbn][qrbn][qrbn]k.xml k[qrbn][qrbn]pk.xml k[qrbn]ppk.xml kpppk.xml"
#fives="k[qrbn][qrbn]k[qrbn].xml"

for xml in $(cd $XMLDIR; ls $twos $threes $fours $fives 2>/dev/null); do
    htb=`echo $xml | sed s/xml/htb/`;
    xml=$XMLDIR/$xml
    if [ -f $xml -a ! -f $htb ]; then
	echo ./hoffman $* -g $xml
    fi
done
